language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
after_success:
  - npm run codecov
notifications: 
  slack:
    secure: "GoWcStRFcPbGOFwxwsbND+snyNbSSo2vyw36gaTM4gMSqjBC2GDe+hqMyLviL8R6Tc8rR6W75L22jxjKM8de9rqD2nl/0KcZouSTmxkX5JhD2VuojalCb+GXAyxFHTZK6uUmHpX/A7duS2k1J/lBUOv0WLZ17NXdv21Z5HCOzC7VvQ0L1K6+H+dKIztCYikgB4WdBS+x/smvjJ6BMMbMzSHEJqg1X8YgO4gw9+Lbxjhx4aiGAE5Kh+wd8JC2Md8MKkEMlTS5CroRXSnQzkbsUk7hYMgMZZXhpkDXOHjBxfS/SahkDDEsa/XlMuYYdOavf79nkzj3bwMCo9zXyhztscL2Kal2ebIb1jDKJFONIeMpffAHSLB5OXqBtnrtXlVLlizIeShm43jewzgTtVLrVw6AQ7XlcE8CeAGshPgRswDJ2fZoAKI8ajLTcmhvZjzaHdqG6mX1GO2QHiSsg8Wkoz9r/UT4Jnw6I+a/+EHShFLjEK+/ofu/SdRwA7G0UZf+UrlBdPU8c30P92OKekyoc3hzX+aqwlxxOlccE8QwSkbXnfh52IwUUgqCo4wgjrEfduu0X20A4tLNZLGLdZsRrlCKmppbDm5iLbGpYg/2Wf+yxDxtMvShrlar78gLlQHCYnckiVvZIilc05xO5pvlYgifSDlBnqf4NpH4e1IvqBM="
deploy:
  provider: heroku
  api_key:
      secure: "WEj1ZkU6db0C520BB1pjsud53XXKXR7u+XXSjYP2/53JedOhP39JftnlUz9MuiOQaLE0+L2EPzF1Nk9jMHfpGHuk51b/6l1/pQ08X8vkndL/u70nO+pgReoKiUB0lU1TtdD4nPfCTx1BdlOOrK3lxNDtP/HNFKCwvRYzmz1BlqWrp4EQynZmJIntpT0cFA6vbUjFZtBPoYdLZdH3kL4d14ftZsGzps2jOL0T4zR3ypsvM9dKOZ1pKb8+7JSxKc6pa5kIfjVsC7FB5GOBXuGAI8QtWahfCLkPD82ZHGw7C0Q7n5VPo6K2F0CPqAT2ejCg5JQJzD0jvVqw9CNMRlBPsPwZwG8HNhSpB9lVPtJTgvxswHHXc8po2jHqia6aIuxUn5DvbP7l3DTjV5ScgcnLcQKGwf6/G+wgtjStu5S8SC6AfK/fZKJtTstT0NiKdesm/6GoBXhr6eV5hdVkAgClq/RGvRyOoH3Y+S29lgP2qgpHJxOZFHGNV2FEGkvyBzmvhbV5y3NMPDNZMA7WtG3S5otsH75Z8UVmyAtdMnhMjoNX6nR9dmNfRpknt2pARUpgUC94wbcOF412PuRh7xQEGkyTbYOgdSQF14NqCP+T9ksfJoCR431wA1qGrP+0L8LuTVV4uHxlqhBpT60W2dfxdTx0En8uDuKySGPMWGR679k="
  app: enkida
